name: Build and Deploy
on:
  - push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️ # Clone the repo
        uses: actions/checkout@v3
        # Install project
      - run: yarn install
      # Build the website
      - run: yarn run build
      # Deploy the "build" folder to "gh-pages" branch
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
